<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RefInstansiSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['id' => '1010', 'nama_instansi' => 'Kementerian Koordinator Bidang Polhukam', 'is_active' => 1],
            ['id' => '1020', 'nama_instansi' => 'Kementerian Koordinator Bidang Perekonomian', 'is_active' => 1],
            ['id' => '1030', 'nama_instansi' => 'Kementerian Koordinator Bidang Kesejahteraan Rakyat', 'is_active' => 1],
            ['id' => '2000', 'nama_instansi' => 'Kementerian Riset dan Teknologi', 'is_active' => 1],
            ['id' => '2010', 'nama_instansi' => 'Kementerian Koperasi Dan UKM', 'is_active' => 1],
            ['id' => '2020', 'nama_instansi' => 'Kementerian Lingkungan Hidup', 'is_active' => 1],
            ['id' => '2040', 'nama_instansi' => 'Kementerian BUMN', 'is_active' => 1],
            ['id' => '2050', 'nama_instansi' => 'Kementerian Negara Pemberdayaan Perempuan dan Perlindungan Anak', 'is_active' => 1],
            ['id' => '2060', 'nama_instansi' => 'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi', 'is_active' => 1],
            ['id' => '2100', 'nama_instansi' => 'Kementerian Pemuda Olahraga', 'is_active' => 1],
            ['id' => '2110', 'nama_instansi' => 'Kementerian Perumahan Rakyat', 'is_active' => 1],
            ['id' => '2120', 'nama_instansi' => 'Kementerian Desa, Pembangunan Daerah Tertinggal dan Transmigrasi', 'is_active' => 1],
            ['id' => '300', 'nama_instansi' => 'PT. Taspen KCU Bandung', 'is_active' => 1],
            ['id' => '3001', 'nama_instansi' => 'Kementerian Dalam Negeri', 'is_active' => 1],
            ['id' => '3002', 'nama_instansi' => 'Kementerian Luar Negeri', 'is_active' => 1],
            ['id' => '3003', 'nama_instansi' => 'Kementerian Pertahanan', 'is_active' => 1],
            ['id' => '3004', 'nama_instansi' => 'Kementerian Hukum dan Hak Asasi Manusia', 'is_active' => 1],
            ['id' => '3005', 'nama_instansi' => 'Kementerian Keuangan', 'is_active' => 1],
            ['id' => '3006', 'nama_instansi' => 'Kementerian Pertanian', 'is_active' => 1],
            ['id' => '3008', 'nama_instansi' => 'Kementerian Energi dan Sumber Daya Mineral', 'is_active' => 1],
            ['id' => '3009', 'nama_instansi' => 'Kementerian Perhubungan', 'is_active' => 1],
            ['id' => '301', 'nama_instansi' => 'PT. Taspen KC Bogor', 'is_active' => 1],
            ['id' => '3010', 'nama_instansi' => 'Kementerian Pendidikan, Kebudayaan dan Riset dan Teknologi', 'is_active' => 1],
            ['id' => '3011', 'nama_instansi' => 'Kementerian Kesehatan', 'is_active' => 1],
            ['id' => '3012', 'nama_instansi' => 'Kementerian Agama', 'is_active' => 1],
            ['id' => '3013', 'nama_instansi' => 'Kementerian Tenaga Kerja dan Transmigrasi', 'is_active' => 1],
            ['id' => '3014', 'nama_instansi' => 'Kementerian Sosial', 'is_active' => 1],
            ['id' => '3015', 'nama_instansi' => 'Kementerian Lingkungan Hidup dan Kehutanan', 'is_active' => 1],
            ['id' => '3016', 'nama_instansi' => 'Kementerian Kelautan Dan Perikanan', 'is_active' => 1],
            ['id' => '3018', 'nama_instansi' => 'Kementerian Komunikasi dan Informatika', 'is_active' => 1],
            ['id' => '3019', 'nama_instansi' => 'Kementerian Perdagangan', 'is_active' => 1],
            ['id' => '302', 'nama_instansi' => 'PT. Taspen KC Tasikmalaya', 'is_active' => 1],
            ['id' => '3020', 'nama_instansi' => 'Kementerian Perindustrian', 'is_active' => 1],
            ['id' => '3021', 'nama_instansi' => 'Kementerian Pekerjaan Umum', 'is_active' => 1],
            ['id' => '3022', 'nama_instansi' => 'Kementerian Pariwisata dan Ekonomi Kreatif', 'is_active' => 1],
            ['id' => '303', 'nama_instansi' => 'PT. Taspen KC Cirebon', 'is_active' => 1],
            ['id' => '304', 'nama_instansi' => 'PT. Taspen KC Serang', 'is_active' => 1],
            ['id' => '305', 'nama_instansi' => 'PT. Taspen KC Bekasi', 'is_active' => 1],
            ['id' => '306', 'nama_instansi' => 'PT. Taspen KC Depok', 'is_active' => 1],
            ['id' => '307', 'nama_instansi' => 'PT. Taspen KC  Tangerang', 'is_active' => 1],
            ['id' => '400', 'nama_instansi' => 'PT. Asabri Bandung', 'is_active' => 1],
            ['id' => '4001', 'nama_instansi' => 'Kementerian Sekretariat Negara', 'is_active' => 1],
            ['id' => '4002', 'nama_instansi' => 'Kejaksaan Agung', 'is_active' => 1],
            ['id' => '4003', 'nama_instansi' => 'Badan Intelijen Negara', 'is_active' => 1],
            ['id' => '4004', 'nama_instansi' => 'Sekretariat Jenderal MPR', 'is_active' => 1],
            ['id' => '4005', 'nama_instansi' => 'Setjen DPA', 'is_active' => 1],
            ['id' => '4006', 'nama_instansi' => 'Sekretariat Jenderal DPR', 'is_active' => 1],
            ['id' => '4007', 'nama_instansi' => 'Mahkamah Agung RI', 'is_active' => 1],
            ['id' => '4008', 'nama_instansi' => 'Badan Pemeriksa Keuangan', 'is_active' => 1],
            ['id' => '4009', 'nama_instansi' => 'Setjen WANTANNAS', 'is_active' => 1],
            ['id' => '401', 'nama_instansi' => 'PT. Asabri Cirebon', 'is_active' => 1],
            ['id' => '4010', 'nama_instansi' => 'Lembaga Sandi Negara', 'is_active' => 1],
            ['id' => '4011', 'nama_instansi' => 'Badan Kepegawaian Negara', 'is_active' => 1],
            ['id' => '4012', 'nama_instansi' => 'Lembaga Administrasi Negara', 'is_active' => 1],
            ['id' => '4013', 'nama_instansi' => 'Lembaga Penerbangan Antariksa Nasional', 'is_active' => 1],
            ['id' => '4014', 'nama_instansi' => 'Lembaga Ilmu Pengetahuan Indonesia', 'is_active' => 1],
            ['id' => '4015', 'nama_instansi' => 'Badan Tenaga Nuklir Nasional', 'is_active' => 1],
            ['id' => '4016', 'nama_instansi' => 'Badan Pusat Statistik', 'is_active' => 1],
            ['id' => '4017', 'nama_instansi' => 'Kementerian PPN/Bappenas', 'is_active' => 1],
            ['id' => '4018', 'nama_instansi' => 'Arsip Nasional Republik Indonesia', 'is_active' => 1],
            ['id' => '4019', 'nama_instansi' => 'Badan Informasi Geospasial', 'is_active' => 1],
            ['id' => '402', 'nama_instansi' => 'PT. Asabri Serang', 'is_active' => 1],
            ['id' => '4020', 'nama_instansi' => 'Badan Kependudukan dan KB Nasional', 'is_active' => 1],
            ['id' => '4021', 'nama_instansi' => 'Badan Koordinasi Penanaman Modal', 'is_active' => 1],
            ['id' => '4022', 'nama_instansi' => 'Badan Pengkajian dan Penerapan Teknologi', 'is_active' => 1],
            ['id' => '4023', 'nama_instansi' => 'Badan Pengawasan Keuangan dan Pembangunan', 'is_active' => 1],
            ['id' => '4024', 'nama_instansi' => 'Badan Pertanahan Nasional', 'is_active' => 1],
            ['id' => '4025', 'nama_instansi' => 'Perpustakaan Nasional RI', 'is_active' => 1],
            ['id' => '4027', 'nama_instansi' => 'Badan Standardisasi Nasional', 'is_active' => 1],
            ['id' => '4028', 'nama_instansi' => 'Badan Pengawas Tenaga Nuklir', 'is_active' => 1],
            ['id' => '4031', 'nama_instansi' => 'Badan Pengawas Obat dan Makanan', 'is_active' => 1],
            ['id' => '4032', 'nama_instansi' => 'Lembaga Ketahanan Nasional RI', 'is_active' => 1],
            ['id' => '4033', 'nama_instansi' => 'Kepolisian Negara', 'is_active' => 1],
            ['id' => '4034', 'nama_instansi' => 'MABES TNI', 'is_active' => 1],
            ['id' => '4035', 'nama_instansi' => 'Badan Meteorologi, Klimatologi dan Geofisika', 'is_active' => 1],
            ['id' => '4036', 'nama_instansi' => 'Sekretariat Kabinet ', 'is_active' => 1],
            ['id' => '4037', 'nama_instansi' => 'Sekretariat Presiden', 'is_active' => 1],
            ['id' => '4038', 'nama_instansi' => 'Sekretariat Wakil Presiden', 'is_active' => 1],
            ['id' => '4039', 'nama_instansi' => 'Sekretariat Militer', 'is_active' => 1],
            ['id' => '4040', 'nama_instansi' => 'Badan Narkotika Nasional', 'is_active' => 1],
            ['id' => '4041', 'nama_instansi' => 'Setjen Komisi Pemilihan Umum', 'is_active' => 1],
            ['id' => '4043', 'nama_instansi' => 'Badan Nasional Penanggulangan Bencana', 'is_active' => 1],
            ['id' => '4044', 'nama_instansi' => 'Setjen KOMNAS HAM', 'is_active' => 1],
            ['id' => '4045', 'nama_instansi' => 'Badan Pengusahaan Kawasan Perdagangan Bebas dan Pelabuhan Bebas Batam', 'is_active' => 1],
            ['id' => '4046', 'nama_instansi' => 'Kepaniteraan dan Sekretariat Jenderal Mahkamah Konstitusi RI', 'is_active' => 1],
            ['id' => '4047', 'nama_instansi' => 'Setjen Komisi Pemberantasan Korupsi', 'is_active' => 1],
            ['id' => '4048', 'nama_instansi' => 'Setjen KORPRI', 'is_active' => 1],
            ['id' => '4049', 'nama_instansi' => 'Sekretariat Jenderal Komisi Yudisial', 'is_active' => 1],
            ['id' => '4050', 'nama_instansi' => 'Setjen Dewan Perwakilan Daerah', 'is_active' => 1],
            ['id' => '4051', 'nama_instansi' => 'Badan Nasional Penempatan Perlind. TKI', 'is_active' => 1],
            ['id' => '4052', 'nama_instansi' => 'Badan Koordinasi Keamanan Laut RI', 'is_active' => 1],
            ['id' => '4053', 'nama_instansi' => 'Badan SAR Nasional', 'is_active' => 1],
            ['id' => '4054', 'nama_instansi' => 'Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah', 'is_active' => 1],
            ['id' => '4055', 'nama_instansi' => 'Pusat Pelaporan dan Analisis Transaksi Keuangan', 'is_active' => 1],
            ['id' => '4056', 'nama_instansi' => 'Ombudsman Republik Indonesia', 'is_active' => 1],
            ['id' => '4057', 'nama_instansi' => 'TELEVISI REPUBLIK INDONESIA', 'is_active' => 1],
            ['id' => '4058', 'nama_instansi' => 'RADIO REPUBLIK INDONESIA', 'is_active' => 1],
            ['id' => '4059', 'nama_instansi' => 'Badan Nasional Pengelola Perbatasan', 'is_active' => 1],
            ['id' => '4060', 'nama_instansi' => 'Badan Nasional Penanggulangan Terorisme', 'is_active' => 1],
            ['id' => '4061', 'nama_instansi' => 'Setjen Komisi Pengawas Persaingan Usaha', 'is_active' => 1],
            ['id' => '4062', 'nama_instansi' => 'Badan Pengawas Pemilihan Umum', 'is_active' => 1],
            ['id' => '4067', 'nama_instansi' => 'Badan Riset dan Inovasi Nasional', 'is_active' => 1],
            ['id' => '5100', 'nama_instansi' => 'Pemerintah Aceh', 'is_active' => 1],
            ['id' => '5101', 'nama_instansi' => 'Pemerintah Kab. Aceh Besar', 'is_active' => 1],
            ['id' => '5102', 'nama_instansi' => 'Pemerintah Kab. Pidie', 'is_active' => 1],
            ['id' => '5103', 'nama_instansi' => 'Pemerintah Kab. Aceh Utara', 'is_active' => 1],
            ['id' => '5104', 'nama_instansi' => 'Pemerintah Kab. Aceh Timur', 'is_active' => 1],
            ['id' => '5105', 'nama_instansi' => 'Pemerintah Kab. Aceh Selatan', 'is_active' => 1],
            ['id' => '5106', 'nama_instansi' => 'Pemerintah Kab. Aceh Barat', 'is_active' => 1],
            ['id' => '5107', 'nama_instansi' => 'Pemerintah Kab. Aceh Tengah', 'is_active' => 1],
            ['id' => '5108', 'nama_instansi' => 'Pemerintah Kab. Aceh Tenggara', 'is_active' => 1],
            ['id' => '5109', 'nama_instansi' => 'Pemerintah Kab. Simeulue', 'is_active' => 1],
            ['id' => '5110', 'nama_instansi' => 'Pemerintah Kab. Bireuen', 'is_active' => 1],
            ['id' => '5111', 'nama_instansi' => 'Pemerintah Kab. Aceh Singkil', 'is_active' => 1],
            ['id' => '5112', 'nama_instansi' => 'Pemerintah Kab. Aceh Barat Daya', 'is_active' => 1],
            ['id' => '5113', 'nama_instansi' => 'Pemerintah Kab. Gayo Lues', 'is_active' => 1],
            ['id' => '5114', 'nama_instansi' => 'Pemerintah Kab. Aceh Tamiang', 'is_active' => 1],
            ['id' => '5115', 'nama_instansi' => 'Pemerintah Kab. Nagan Raya', 'is_active' => 1],
            ['id' => '5116', 'nama_instansi' => 'Pemerintah Kab. Aceh Jaya', 'is_active' => 1],
            ['id' => '5117', 'nama_instansi' => 'Pemerintah Kab. Bener Meriah', 'is_active' => 1],
            ['id' => '5118', 'nama_instansi' => 'Pemerintah Kab. Pidie Jaya', 'is_active' => 1],
            ['id' => '5171', 'nama_instansi' => 'Pemerintah Kota Sabang', 'is_active' => 1],
            ['id' => '5172', 'nama_instansi' => 'Pemerintah Kota Banda Aceh', 'is_active' => 1],
            ['id' => '5173', 'nama_instansi' => 'Pemerintah Kota Langsa', 'is_active' => 1],
            ['id' => '5174', 'nama_instansi' => 'Pemerintah Kota Lhokseumawe', 'is_active' => 1],
            ['id' => '5175', 'nama_instansi' => 'Pemerintah Kota Subulussalam', 'is_active' => 1],
            ['id' => '5200', 'nama_instansi' => 'Pemerintah Provinsi Sumatera Utara', 'is_active' => 1],
            ['id' => '5201', 'nama_instansi' => 'Pemerintah Kab. Deli Serdang', 'is_active' => 1],
            ['id' => '5202', 'nama_instansi' => 'Pemerintah Kab. Karo', 'is_active' => 1],
            ['id' => '5203', 'nama_instansi' => 'Pemerintah Kab. Langkat', 'is_active' => 1],
            ['id' => '5204', 'nama_instansi' => 'Pemerintah Kab. Tapanuli Tengah', 'is_active' => 1],
            ['id' => '5205', 'nama_instansi' => 'Pemerintah Kab. Simalungun', 'is_active' => 1],
            ['id' => '5206', 'nama_instansi' => 'Pemerintah Kab. Labuhanbatu', 'is_active' => 1],
            ['id' => '5207', 'nama_instansi' => 'Pemerintah Kab. Dairi', 'is_active' => 1],
            ['id' => '5208', 'nama_instansi' => 'Pemerintah Kab. Tapanuli Utara', 'is_active' => 1],
            ['id' => '5209', 'nama_instansi' => 'Pemerintah Kab. Tapanuli Selatan', 'is_active' => 1],
            ['id' => '5210', 'nama_instansi' => 'Pemerintah Kab. Asahan', 'is_active' => 1],
            ['id' => '5211', 'nama_instansi' => 'Pemerintah Kab. Nias', 'is_active' => 1],
            ['id' => '5212', 'nama_instansi' => 'Pemerintah Kab. Toba Samosir', 'is_active' => 1],
            ['id' => '5213', 'nama_instansi' => 'Pemerintah Kab. Mandailing Natal', 'is_active' => 1],
            ['id' => '5214', 'nama_instansi' => 'Pemerintah Kab. Nias Selatan', 'is_active' => 1],
            ['id' => '5215', 'nama_instansi' => 'Pemerintah Kab. Humbang Hasundutan', 'is_active' => 1],
            ['id' => '5216', 'nama_instansi' => 'Pemerintah Kab. Pakpak Bharat', 'is_active' => 1],
            ['id' => '5217', 'nama_instansi' => 'Pemerintah Kab. Samosir', 'is_active' => 1],
            ['id' => '5218', 'nama_instansi' => 'Pemerintah Kab. Serdang Bedagai', 'is_active' => 1],
            ['id' => '5219', 'nama_instansi' => 'Pemerintah Kab. Padang Lawas', 'is_active' => 1],
            ['id' => '5220', 'nama_instansi' => 'Pemerintah Kab. Padang Lawas Utara', 'is_active' => 1],
            ['id' => '5221', 'nama_instansi' => 'Pemerintah Kab. Batubara', 'is_active' => 1],
            ['id' => '5222', 'nama_instansi' => 'Pemerintah Kab. Labuhanbatu Selatan', 'is_active' => 1],
            ['id' => '5223', 'nama_instansi' => 'Pemerintah Kab. Labuhanbatu Utara', 'is_active' => 1],
            ['id' => '5224', 'nama_instansi' => 'Pemerintah Kab. Nias Barat', 'is_active' => 1],
            ['id' => '5225', 'nama_instansi' => 'Pemerintah Kab. Nias Utara', 'is_active' => 1],
            ['id' => '5271', 'nama_instansi' => 'Pemerintah Kota Medan', 'is_active' => 1],
            ['id' => '5272', 'nama_instansi' => 'Pemerintah Kota Tebing Tinggi', 'is_active' => 1],
            ['id' => '5273', 'nama_instansi' => 'Pemerintah Kota Binjai', 'is_active' => 1],
            ['id' => '5274', 'nama_instansi' => 'Pemerintah Kota Pematang Siantar', 'is_active' => 1],
            ['id' => '5275', 'nama_instansi' => 'Pemerintah Kota Tanjung Balai', 'is_active' => 1],
            ['id' => '5276', 'nama_instansi' => 'Pemerintah Kota Sibolga', 'is_active' => 1],
            ['id' => '5277', 'nama_instansi' => 'Pemerintah Kota Padangsidimpuan', 'is_active' => 1],
            ['id' => '5278', 'nama_instansi' => 'Pemerintah Kota Gunung Sitoli', 'is_active' => 1],
            ['id' => '5300', 'nama_instansi' => 'Pemerintah Provinsi Riau', 'is_active' => 1],
            ['id' => '5301', 'nama_instansi' => 'Pemerintah Kab. Kampar', 'is_active' => 1],
            ['id' => '5302', 'nama_instansi' => 'Pemerintah Kab. Bengkalis', 'is_active' => 1],
            ['id' => '5304', 'nama_instansi' => 'Pemerintah Kab. Indragiri Hulu', 'is_active' => 1],
            ['id' => '5305', 'nama_instansi' => 'Pemerintah Kab. Indragiri Hilir', 'is_active' => 1],
            ['id' => '5306', 'nama_instansi' => 'Pemerintah Kab. Pelalawan', 'is_active' => 1],
            ['id' => '5307', 'nama_instansi' => 'Pemerintah Kab. Rokan Hulu', 'is_active' => 1],
            ['id' => '5308', 'nama_instansi' => 'Pemerintah Kab. Rokan Hilir', 'is_active' => 1],
            ['id' => '5309', 'nama_instansi' => 'Pemerintah Kab. Siak', 'is_active' => 1],
            ['id' => '5312', 'nama_instansi' => 'Pemerintah Kab. Kuantan Singingi', 'is_active' => 1],
            ['id' => '5313', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Meranti', 'is_active' => 1],
            ['id' => '5371', 'nama_instansi' => 'Pemerintah Kota Pekanbaru', 'is_active' => 1],
            ['id' => '5373', 'nama_instansi' => 'Pemerintah Kota Dumai', 'is_active' => 1],
            ['id' => '5400', 'nama_instansi' => 'Pemerintah Provinsi Sumatera Barat', 'is_active' => 1],
            ['id' => '5401', 'nama_instansi' => 'Pemerintah Kab. Agam', 'is_active' => 1],
            ['id' => '5402', 'nama_instansi' => 'Pemerintah Kab. Pasaman', 'is_active' => 1],
            ['id' => '5403', 'nama_instansi' => 'Pemerintah Kab. Limapuluh Kota', 'is_active' => 1],
            ['id' => '5404', 'nama_instansi' => 'Pemerintah Kab. Solok', 'is_active' => 1],
            ['id' => '5405', 'nama_instansi' => 'Pemerintah Kab. Padang Pariaman', 'is_active' => 1],
            ['id' => '5406', 'nama_instansi' => 'Pemerintah Kab. Pesisir Selatan', 'is_active' => 1],
            ['id' => '5407', 'nama_instansi' => 'Pemerintah Kab. Tanah Datar', 'is_active' => 1],
            ['id' => '5408', 'nama_instansi' => 'Pemerintah Kab. Sijunjung', 'is_active' => 1],
            ['id' => '5409', 'nama_instansi' => 'Pemerintah Kab. Kep. Mentawai', 'is_active' => 1],
            ['id' => '5410', 'nama_instansi' => 'Pemerintah Kab. Solok Selatan', 'is_active' => 1],
            ['id' => '5411', 'nama_instansi' => 'Pemerintah Kab. Dharmasraya', 'is_active' => 1],
            ['id' => '5412', 'nama_instansi' => 'Pemerintah Kab. Pasaman Barat', 'is_active' => 1],
            ['id' => '5471', 'nama_instansi' => 'Pemerintah Kota Bukittinggi', 'is_active' => 1],
            ['id' => '5472', 'nama_instansi' => 'Pemerintah Kota Padang Panjang', 'is_active' => 1],
            ['id' => '5473', 'nama_instansi' => 'Pemerintah Kota Sawahlunto', 'is_active' => 1],
            ['id' => '5474', 'nama_instansi' => 'Pemerintah Kota Solok', 'is_active' => 1],
            ['id' => '5475', 'nama_instansi' => 'Pemerintah Kota Padang', 'is_active' => 1],
            ['id' => '5476', 'nama_instansi' => 'Pemerintah Kota Payakumbuh', 'is_active' => 1],
            ['id' => '5477', 'nama_instansi' => 'Pemerintah Kota Pariaman', 'is_active' => 1],
            ['id' => '5500', 'nama_instansi' => 'Pemerintah Provinsi Jambi', 'is_active' => 1],
            ['id' => '5501', 'nama_instansi' => 'Pemerintah Kab. Batang Hari', 'is_active' => 1],
            ['id' => '5502', 'nama_instansi' => 'Pemerintah Kab. Tanjung Jabung Barat', 'is_active' => 1],
            ['id' => '5503', 'nama_instansi' => 'Pemerintah Kab. Bungo', 'is_active' => 1],
            ['id' => '5504', 'nama_instansi' => 'Pemerintah Kab. Merangin', 'is_active' => 1],
            ['id' => '5505', 'nama_instansi' => 'Pemerintah Kab. Kerinci', 'is_active' => 1],
            ['id' => '5506', 'nama_instansi' => 'Pemerintah Kab. Sarolangun', 'is_active' => 1],
            ['id' => '5507', 'nama_instansi' => 'Pemerintah Kab. Tebo', 'is_active' => 1],
            ['id' => '5508', 'nama_instansi' => 'Pemerintah Kab. Muaro Jambi', 'is_active' => 1],
            ['id' => '5509', 'nama_instansi' => 'Pemerintah Kab. Tanjung Jabung Timur', 'is_active' => 1],
            ['id' => '5571', 'nama_instansi' => 'Pemerintah Kota Jambi', 'is_active' => 1],
            ['id' => '5572', 'nama_instansi' => 'Pemerintah Kota Sungai Penuh', 'is_active' => 1],
            ['id' => '5600', 'nama_instansi' => 'Pemerintah Provinsi Sumatera Selatan', 'is_active' => 1],
            ['id' => '5601', 'nama_instansi' => 'Pemerintah Kab. Musi Banyuasin', 'is_active' => 1],
            ['id' => '5602', 'nama_instansi' => 'Pemerintah Kab. Ogan Komering Ulu', 'is_active' => 1],
            ['id' => '5603', 'nama_instansi' => 'Pemerintah Kab. Muara Enim', 'is_active' => 1],
            ['id' => '5604', 'nama_instansi' => 'Pemerintah Kab. Lahat', 'is_active' => 1],
            ['id' => '5605', 'nama_instansi' => 'Pemerintah Kab. Musi Rawas', 'is_active' => 1],
            ['id' => '5606', 'nama_instansi' => 'Pemerintah Kab. Ogan Komering Ilir', 'is_active' => 1],
            ['id' => '5607', 'nama_instansi' => 'Pemerintah Kab. Banyuasin', 'is_active' => 1],
            ['id' => '5608', 'nama_instansi' => 'Pemerintah Kab. Ogan Komering Ulu Timur', 'is_active' => 1],
            ['id' => '5609', 'nama_instansi' => 'Pemerintah Kab. Ogan Komering Ulu Sel.', 'is_active' => 1],
            ['id' => '5610', 'nama_instansi' => 'Pemerintah Kab. Ogan Ilir', 'is_active' => 1],
            ['id' => '5611', 'nama_instansi' => 'Pemerintah Kab. Empat Lawang', 'is_active' => 1],
            ['id' => '5671', 'nama_instansi' => 'Pemerintah Kota Palembang', 'is_active' => 1],
            ['id' => '5672', 'nama_instansi' => 'Pemerintah Kota Pagar Alam', 'is_active' => 1],
            ['id' => '5673', 'nama_instansi' => 'Pemerintah Kota Lubuk Linggau', 'is_active' => 1],
            ['id' => '5674', 'nama_instansi' => 'Pemerintah Kota Prabumulih', 'is_active' => 1],
            ['id' => '5675', 'nama_instansi' => 'Pemerintah Kab. Penukal Abab Lematang Ilir', 'is_active' => 1],
            ['id' => '5700', 'nama_instansi' => 'Pemerintah Provinsi Kep. Bangka Belitung', 'is_active' => 1],
            ['id' => '5701', 'nama_instansi' => 'Pemerintah Kab. Bangka', 'is_active' => 1],
            ['id' => '5702', 'nama_instansi' => 'Pemerintah Kab. Belitung', 'is_active' => 1],
            ['id' => '5703', 'nama_instansi' => 'Pemerintah Kab. Bangka Barat', 'is_active' => 1],
            ['id' => '5704', 'nama_instansi' => 'Pemerintah Kab. Bangka Tengah', 'is_active' => 1],
            ['id' => '5705', 'nama_instansi' => 'Pemerintah Kab. Bangka Selatan', 'is_active' => 1],
            ['id' => '5706', 'nama_instansi' => 'Pemerintah Kab. Belitung Timur', 'is_active' => 1],
            ['id' => '5771', 'nama_instansi' => 'Pemerintah Kota Pangkal Pinang', 'is_active' => 1],
            ['id' => '5800', 'nama_instansi' => 'Pemerintah Provinsi Bengkulu', 'is_active' => 1],
            ['id' => '5801', 'nama_instansi' => 'Pemerintah Kab. Bengkulu Utara', 'is_active' => 1],
            ['id' => '5802', 'nama_instansi' => 'Pemerintah Kab. Bengkulu Selatan', 'is_active' => 1],
            ['id' => '5803', 'nama_instansi' => 'Pemerintah Kab. Rejang Lebong', 'is_active' => 1],
            ['id' => '5804', 'nama_instansi' => 'Pemerintah Kab. Kaur', 'is_active' => 1],
            ['id' => '5805', 'nama_instansi' => 'Pemerintah Kab. Seluma', 'is_active' => 1],
            ['id' => '5806', 'nama_instansi' => 'Pemerintah Kab. Mukomuko', 'is_active' => 1],
            ['id' => '5807', 'nama_instansi' => 'Pemerintah Kab. Kepahiang', 'is_active' => 1],
            ['id' => '5808', 'nama_instansi' => 'Pemerintah Kab. Lebong', 'is_active' => 1],
            ['id' => '5809', 'nama_instansi' => 'Pemerintah Kab. Bengkulu Tengah', 'is_active' => 1],
            ['id' => '5871', 'nama_instansi' => 'Pemerintah Kota Bengkulu', 'is_active' => 1],
            ['id' => '5900', 'nama_instansi' => 'Pemerintah Provinsi Lampung', 'is_active' => 1],
            ['id' => '5901', 'nama_instansi' => 'Pemerintah Kab. Lampung Selatan', 'is_active' => 1],
            ['id' => '5902', 'nama_instansi' => 'Pemerintah Kab. Lampung Tengah', 'is_active' => 1],
            ['id' => '5903', 'nama_instansi' => 'Pemerintah Kab. Lampung Utara', 'is_active' => 1],
            ['id' => '5904', 'nama_instansi' => 'Pemerintah Kab. Lampung Barat', 'is_active' => 1],
            ['id' => '5905', 'nama_instansi' => 'Pemerintah Kab. Tulang Bawang', 'is_active' => 1],
            ['id' => '5906', 'nama_instansi' => 'Pemerintah Kab. Tanggamus', 'is_active' => 1],
            ['id' => '5907', 'nama_instansi' => 'Pemerintah Kab. Way Kanan', 'is_active' => 1],
            ['id' => '5908', 'nama_instansi' => 'Pemerintah Kab. Lampung Timur', 'is_active' => 1],
            ['id' => '5909', 'nama_instansi' => 'Pemerintah Kab. Pesawaran', 'is_active' => 1],
            ['id' => '5910', 'nama_instansi' => 'Pemerintah Kab.Tulang Bawang Barat', 'is_active' => 1],
            ['id' => '5911', 'nama_instansi' => 'Pemerintah Kab. Pringsewu', 'is_active' => 1],
            ['id' => '5912', 'nama_instansi' => 'Pemerintah Kab. Mesuji', 'is_active' => 1],
            ['id' => '5913', 'nama_instansi' => 'Pemerintah Kab. Pesisir Barat', 'is_active' => 1],
            ['id' => '5971', 'nama_instansi' => 'Pemerintah Kota Metro', 'is_active' => 1],
            ['id' => '5972', 'nama_instansi' => 'Pemerintah Kota Bandar Lampung', 'is_active' => 1],
            ['id' => '6000', 'nama_instansi' => 'Pemerintah Provinsi Daerah Khusus Ibukota Jakarta', 'is_active' => 1],
            ['id' => '6001', 'nama_instansi' => 'Kab. Kepulauan Seribu', 'is_active' => 1],
            ['id' => '6100', 'nama_instansi' => 'Pemerintah Provinsi Jawa Barat', 'is_active' => 1],
            ['id' => '6101', 'nama_instansi' => 'Pemerintah Kab. Bogor', 'is_active' => 1],
            ['id' => '6102', 'nama_instansi' => 'Pemerintah Kab. Sukabumi', 'is_active' => 1],
            ['id' => '6103', 'nama_instansi' => 'Pemerintah Kab. Cianjur', 'is_active' => 1],
            ['id' => '6104', 'nama_instansi' => 'Pemerintah Kab. Bekasi', 'is_active' => 1],
            ['id' => '6105', 'nama_instansi' => 'Pemerintah Kab. Karawang', 'is_active' => 1],
            ['id' => '6106', 'nama_instansi' => 'Pemerintah Kab. Purwakarta', 'is_active' => 1],
            ['id' => '6107', 'nama_instansi' => 'Pemerintah Kab. Subang', 'is_active' => 1],
            ['id' => '6108', 'nama_instansi' => 'Pemerintah Kab. Bandung', 'is_active' => 1],
            ['id' => '6109', 'nama_instansi' => 'Pemerintah Kab. Sumedang', 'is_active' => 1],
            ['id' => '6110', 'nama_instansi' => 'Pemerintah Kab. Garut', 'is_active' => 1],
            ['id' => '6111', 'nama_instansi' => 'Pemerintah Kab. Tasikmalaya', 'is_active' => 1],
            ['id' => '6112', 'nama_instansi' => 'Pemerintah Kab. Ciamis', 'is_active' => 1],
            ['id' => '6113', 'nama_instansi' => 'Pemerintah Kab. Cirebon', 'is_active' => 1],
            ['id' => '6114', 'nama_instansi' => 'Pemerintah Kab. Kuningan', 'is_active' => 1],
            ['id' => '6115', 'nama_instansi' => 'Pemerintah Kab. Indramayu', 'is_active' => 1],
            ['id' => '6116', 'nama_instansi' => 'Pemerintah Kab. Majalengka', 'is_active' => 1],
            ['id' => '6117', 'nama_instansi' => 'Pemerintah Kab. Bandung Barat', 'is_active' => 1],
            ['id' => '6118', 'nama_instansi' => 'Pemerintah Kab. Pangandaran', 'is_active' => 1],
            ['id' => '6171', 'nama_instansi' => 'Pemerintah Kota Bandung', 'is_active' => 1],
            ['id' => '6172', 'nama_instansi' => 'Pemerintah Kota  Bogor', 'is_active' => 1],
            ['id' => '6173', 'nama_instansi' => 'Pemerintah Kota Sukabumi', 'is_active' => 1],
            ['id' => '6174', 'nama_instansi' => 'Pemerintah Kota  Cirebon', 'is_active' => 1],
            ['id' => '6175', 'nama_instansi' => 'Pemerintah Kota  Bekasi', 'is_active' => 1],
            ['id' => '6176', 'nama_instansi' => 'Pemerintah Kota Depok', 'is_active' => 1],
            ['id' => '6177', 'nama_instansi' => 'Pemerintah Kota Cimahi', 'is_active' => 1],
            ['id' => '6178', 'nama_instansi' => 'Pemerintah Kota Tasikmalaya', 'is_active' => 1],
            ['id' => '6179', 'nama_instansi' => 'Pemerintah Kota Banjar', 'is_active' => 1],
            ['id' => '6200', 'nama_instansi' => 'Pemerintah Provinsi Banten', 'is_active' => 1],
            ['id' => '6201', 'nama_instansi' => 'Pemerintah Kab. Serang', 'is_active' => 1],
            ['id' => '6202', 'nama_instansi' => 'Pemerintah Kab. Pandeglang', 'is_active' => 1],
            ['id' => '6203', 'nama_instansi' => 'Pemerintah Kab. Lebak', 'is_active' => 1],
            ['id' => '6204', 'nama_instansi' => 'Pemerintah Kab. Tangerang', 'is_active' => 1],
            ['id' => '6271', 'nama_instansi' => 'Pemerintah Kota Tangerang', 'is_active' => 1],
            ['id' => '6272', 'nama_instansi' => 'Pemerintah Kota Cilegon', 'is_active' => 1],
            ['id' => '6273', 'nama_instansi' => 'Pemerintah Kota Serang', 'is_active' => 1],
            ['id' => '6274', 'nama_instansi' => 'Pemerintah Kota Tangerang Selatan', 'is_active' => 1],
            ['id' => '6300', 'nama_instansi' => 'Pemerintah Daerah D I Yogyakarta', 'is_active' => 1],
            ['id' => '6301', 'nama_instansi' => 'Pemerintah Kab. Bantul', 'is_active' => 1],
            ['id' => '6302', 'nama_instansi' => 'Pemerintah Kab. Sleman', 'is_active' => 1],
            ['id' => '6303', 'nama_instansi' => 'Pemerintah Kab. Gunung Kidul', 'is_active' => 1],
            ['id' => '6304', 'nama_instansi' => 'Pemerintah Kab. Kulon Progo', 'is_active' => 1],
            ['id' => '6371', 'nama_instansi' => 'Pemerintah Kota Yogyakarta', 'is_active' => 1],
            ['id' => '6400', 'nama_instansi' => 'Pemerintah Provinsi Jawa Tengah', 'is_active' => 1],
            ['id' => '6401', 'nama_instansi' => 'Pemerintah Kab. Semarang', 'is_active' => 1],
            ['id' => '6402', 'nama_instansi' => 'Pemerintah Kab. Kendal', 'is_active' => 1],
            ['id' => '6403', 'nama_instansi' => 'Pemerintah Kab. Demak', 'is_active' => 1],
            ['id' => '6404', 'nama_instansi' => 'Pemerintah Kab. Grobogan', 'is_active' => 1],
            ['id' => '6405', 'nama_instansi' => 'Pemerintah Kab. Pekalongan', 'is_active' => 1],
            ['id' => '6406', 'nama_instansi' => 'Pemerintah Kab. Batang', 'is_active' => 1],
            ['id' => '6407', 'nama_instansi' => 'Pemerintah Kab. Tegal', 'is_active' => 1],
            ['id' => '6408', 'nama_instansi' => 'Pemerintah Kab. Brebes', 'is_active' => 1],
            ['id' => '6409', 'nama_instansi' => 'Pemerintah Kab. Pati', 'is_active' => 1],
            ['id' => '6410', 'nama_instansi' => 'Pemerintah Kab. Kudus', 'is_active' => 1],
            ['id' => '6411', 'nama_instansi' => 'Pemerintah Kab. Pemalang', 'is_active' => 1],
            ['id' => '6412', 'nama_instansi' => 'Pemerintah Kab. Jepara', 'is_active' => 1],
            ['id' => '6413', 'nama_instansi' => 'Pemerintah Kab. Rembang', 'is_active' => 1],
            ['id' => '6414', 'nama_instansi' => 'Pemerintah Kab. Blora', 'is_active' => 1],
            ['id' => '6415', 'nama_instansi' => 'Pemerintah Kab. Banyumas', 'is_active' => 1],
            ['id' => '6416', 'nama_instansi' => 'Pemerintah Kab. Cilacap', 'is_active' => 1],
            ['id' => '6417', 'nama_instansi' => 'Pemerintah Kab. Purbalingga', 'is_active' => 1],
            ['id' => '6418', 'nama_instansi' => 'Pemerintah Kab. Banjarnegara', 'is_active' => 1],
            ['id' => '6419', 'nama_instansi' => 'Pemerintah Kab. Magelang', 'is_active' => 1],
            ['id' => '6420', 'nama_instansi' => 'Pemerintah Kab. Temanggung', 'is_active' => 1],
            ['id' => '6421', 'nama_instansi' => 'Pemerintah Kab. Wonosobo', 'is_active' => 1],
            ['id' => '6422', 'nama_instansi' => 'Pemerintah Kab. Purworejo', 'is_active' => 1],
            ['id' => '6423', 'nama_instansi' => 'Pemerintah Kab. Kebumen', 'is_active' => 1],
            ['id' => '6424', 'nama_instansi' => 'Pemerintah Kab. Klaten', 'is_active' => 1],
            ['id' => '6425', 'nama_instansi' => 'Pemerintah Kab. Boyolali', 'is_active' => 1],
            ['id' => '6426', 'nama_instansi' => 'Pemerintah Kab. Sragen', 'is_active' => 1],
            ['id' => '6427', 'nama_instansi' => 'Pemerintah Kab. Sukoharjo', 'is_active' => 1],
            ['id' => '6428', 'nama_instansi' => 'Pemerintah Kab. Karanganyar', 'is_active' => 1],
            ['id' => '6429', 'nama_instansi' => 'Pemerintah Kab. Wonogiri', 'is_active' => 1],
            ['id' => '6471', 'nama_instansi' => 'Pemerintah Kota Semarang', 'is_active' => 1],
            ['id' => '6472', 'nama_instansi' => 'Pemerintah Kota Salatiga', 'is_active' => 1],
            ['id' => '6473', 'nama_instansi' => 'Pemerintah Kota  Pekalongan', 'is_active' => 1],
            ['id' => '6474', 'nama_instansi' => 'Pemerintah Kota Tegal', 'is_active' => 1],
            ['id' => '6475', 'nama_instansi' => 'Pemerintah Kota Magelang', 'is_active' => 1],
            ['id' => '6476', 'nama_instansi' => 'Pemerintah Kota Surakarta', 'is_active' => 1],
            ['id' => '6500', 'nama_instansi' => 'Pemerintah Provinsi Jawa Timur', 'is_active' => 1],
            ['id' => '6501', 'nama_instansi' => 'Pemerintah Kab. Gresik', 'is_active' => 1],
            ['id' => '6502', 'nama_instansi' => 'Pemerintah Kab. Mojokerto', 'is_active' => 1],
            ['id' => '6503', 'nama_instansi' => 'Pemerintah Kab.  Sidoarjo', 'is_active' => 1],
            ['id' => '6504', 'nama_instansi' => 'Pemerintah Kab. Jombang', 'is_active' => 1],
            ['id' => '6505', 'nama_instansi' => 'Pemerintah Kab. Sampang', 'is_active' => 1],
            ['id' => '6506', 'nama_instansi' => 'Pemerintah Kab. Pamekasan', 'is_active' => 1],
            ['id' => '6507', 'nama_instansi' => 'Pemerintah Kab. Sumenep', 'is_active' => 1],
            ['id' => '6508', 'nama_instansi' => 'Pemerintah Kab. Bangkalan', 'is_active' => 1],
            ['id' => '6509', 'nama_instansi' => 'Pemerintah Kab. Bondowoso', 'is_active' => 1],
            ['id' => '6510', 'nama_instansi' => 'Pemerintah Kab. Situbondo', 'is_active' => 1],
            ['id' => '6511', 'nama_instansi' => 'Pemerintah Kab. Banyuwangi', 'is_active' => 1],
            ['id' => '6512', 'nama_instansi' => 'Pemerintah Kab. Jember', 'is_active' => 1],
            ['id' => '6513', 'nama_instansi' => 'Pemerintah Kab. Malang', 'is_active' => 1],
            ['id' => '6514', 'nama_instansi' => 'Pemerintah Kab. Pasuruan', 'is_active' => 1],
            ['id' => '6515', 'nama_instansi' => 'Pemerintah Kab. Probolinggo', 'is_active' => 1],
            ['id' => '6516', 'nama_instansi' => 'Pemerintah Kab. Lumajang', 'is_active' => 1],
            ['id' => '6517', 'nama_instansi' => 'Pemerintah Kab. Kediri', 'is_active' => 1],
            ['id' => '6518', 'nama_instansi' => 'Pemerintah Kab. Tulungagung', 'is_active' => 1],
            ['id' => '6519', 'nama_instansi' => 'Pemerintah Kab. Nganjuk', 'is_active' => 1],
            ['id' => '6520', 'nama_instansi' => 'Pemerintah Kab. Trenggalek', 'is_active' => 1],
            ['id' => '6521', 'nama_instansi' => 'Pemerintah Kab. Blitar', 'is_active' => 1],
            ['id' => '6522', 'nama_instansi' => 'Pemerintah Kab. Madiun', 'is_active' => 1],
            ['id' => '6523', 'nama_instansi' => 'Pemerintah Kab. Ngawi', 'is_active' => 1],
            ['id' => '6524', 'nama_instansi' => 'Pemerintah Kab. Magetan', 'is_active' => 1],
            ['id' => '6525', 'nama_instansi' => 'Pemerintah Kab. Ponorogo', 'is_active' => 1],
            ['id' => '6526', 'nama_instansi' => 'Pemerintah Kab. Pacitan', 'is_active' => 1],
            ['id' => '6527', 'nama_instansi' => 'Pemerintah Kab. Bojonegoro', 'is_active' => 1],
            ['id' => '6528', 'nama_instansi' => 'Pemerintah Kab. Tuban', 'is_active' => 1],
            ['id' => '6529', 'nama_instansi' => 'Pemerintah Kab. Lamongan', 'is_active' => 1],
            ['id' => '6571', 'nama_instansi' => 'Pemerintah Kota Surabaya', 'is_active' => 1],
            ['id' => '6572', 'nama_instansi' => 'Pemerintah Kota Mojokerto', 'is_active' => 1],
            ['id' => '6573', 'nama_instansi' => 'Pemerintah Kota Malang', 'is_active' => 1],
            ['id' => '6574', 'nama_instansi' => 'Pemerintah Kota Pasuruan', 'is_active' => 1],
            ['id' => '6575', 'nama_instansi' => 'Pemerintah Kota Probolinggo', 'is_active' => 1],
            ['id' => '6576', 'nama_instansi' => 'Pemerintah Kota Blitar', 'is_active' => 1],
            ['id' => '6577', 'nama_instansi' => 'Pemerintah Kota Kediri', 'is_active' => 1],
            ['id' => '6578', 'nama_instansi' => 'Pemerintah Kota Madiun', 'is_active' => 1],
            ['id' => '6579', 'nama_instansi' => 'Pemerintah Kota Batu', 'is_active' => 1],
            ['id' => '6600', 'nama_instansi' => 'Pemerintah Provinsi Kalimantan Barat', 'is_active' => 1],
            ['id' => '6601', 'nama_instansi' => 'Pemerintah Kab. Sambas', 'is_active' => 1],
            ['id' => '6602', 'nama_instansi' => 'Pemerintah Kab. Sanggau', 'is_active' => 1],
            ['id' => '6603', 'nama_instansi' => 'Pemerintah Kab. Sintang', 'is_active' => 1],
            ['id' => '6604', 'nama_instansi' => 'Pemerintah Kab. Pontianak', 'is_active' => 1],
            ['id' => '6605', 'nama_instansi' => 'Pemerintah Kab. Kapuas Hulu', 'is_active' => 1],
            ['id' => '6606', 'nama_instansi' => 'Pemerintah Kab. Ketapang', 'is_active' => 1],
            ['id' => '6607', 'nama_instansi' => 'Pemerintah Kab.Bengkayang', 'is_active' => 1],
            ['id' => '6608', 'nama_instansi' => 'Pemerintah Kab.Landak', 'is_active' => 1],
            ['id' => '6609', 'nama_instansi' => 'Pemerintah Kab. Melawi', 'is_active' => 1],
            ['id' => '6610', 'nama_instansi' => 'Pemerintah Kab. Sekadau', 'is_active' => 1],
            ['id' => '6611', 'nama_instansi' => 'Pemerintah Kab. Kubu Raya', 'is_active' => 1],
            ['id' => '6612', 'nama_instansi' => 'Pemerintah Kab. Kayong Utara', 'is_active' => 1],
            ['id' => '6671', 'nama_instansi' => 'Pemerintah Kota Pontianak', 'is_active' => 1],
            ['id' => '6672', 'nama_instansi' => 'Pemerintah Kota Singkawang', 'is_active' => 1],
            ['id' => '6700', 'nama_instansi' => 'Pemerintah Provinsi Kalimantan Tengah', 'is_active' => 1],
            ['id' => '6701', 'nama_instansi' => 'Pemerintah Kab. Kapuas', 'is_active' => 1],
            ['id' => '6702', 'nama_instansi' => 'Pemerintah Kab. Barito Utara', 'is_active' => 1],
            ['id' => '6703', 'nama_instansi' => 'Pemerintah Kab. Barito Selatan', 'is_active' => 1],
            ['id' => '6704', 'nama_instansi' => 'Pemerintah Kab. Kotawaringin Timur', 'is_active' => 1],
            ['id' => '6705', 'nama_instansi' => 'Pemerintah Kab. Kotawaringin Barat', 'is_active' => 1],
            ['id' => '6706', 'nama_instansi' => 'Pemerintah Kab. Pulang Pisau', 'is_active' => 1],
            ['id' => '6707', 'nama_instansi' => 'Pemerintah Kab. Gunung Mas', 'is_active' => 1],
            ['id' => '6708', 'nama_instansi' => 'Pemerintah Kab. Lamandau', 'is_active' => 1],
            ['id' => '6709', 'nama_instansi' => 'Pemerintah Kab. Sukamara', 'is_active' => 1],
            ['id' => '6710', 'nama_instansi' => 'Pemerintah Kab. Murung Raya', 'is_active' => 1],
            ['id' => '6711', 'nama_instansi' => 'Pemerintah Kab. Katingan', 'is_active' => 1],
            ['id' => '6712', 'nama_instansi' => 'Pemerintah Kab. Seruyan', 'is_active' => 1],
            ['id' => '6713', 'nama_instansi' => 'Pemerintah Kab. Barito Timur', 'is_active' => 1],
            ['id' => '6771', 'nama_instansi' => 'Pemerintah Kota Palangka Raya', 'is_active' => 1],
            ['id' => '6800', 'nama_instansi' => 'Pemerintah Provinsi Kalimantan Selatan', 'is_active' => 1],
            ['id' => '6801', 'nama_instansi' => 'Pemerintah Kab. Banjar', 'is_active' => 1],
            ['id' => '6802', 'nama_instansi' => 'Pemerintah Kab. Tanah Laut', 'is_active' => 1],
            ['id' => '6803', 'nama_instansi' => 'Pemerintah Kab. Tapin', 'is_active' => 1],
            ['id' => '6804', 'nama_instansi' => 'Pemerintah Kab. Hulu Sungai Selatan', 'is_active' => 1],
            ['id' => '6805', 'nama_instansi' => 'Pemerintah Kab. Hulu Sungai Tengah', 'is_active' => 1],
            ['id' => '6806', 'nama_instansi' => 'Pemerintah Kab. Barito Kuala', 'is_active' => 1],
            ['id' => '6807', 'nama_instansi' => 'Pemerintah Kab. Tabalong', 'is_active' => 1],
            ['id' => '6808', 'nama_instansi' => 'Pemerintah Kab. Kotabaru', 'is_active' => 1],
            ['id' => '6809', 'nama_instansi' => 'Pemerintah Kab. Hulu Sungai Utara', 'is_active' => 1],
            ['id' => '6810', 'nama_instansi' => 'Pemerintah Kab. Tanah Bumbu', 'is_active' => 1],
            ['id' => '6811', 'nama_instansi' => 'Pemerintah Kab. Balangan', 'is_active' => 1],
            ['id' => '6871', 'nama_instansi' => 'Pemerintah Kota Banjarmasin', 'is_active' => 1],
            ['id' => '6872', 'nama_instansi' => 'Pemerintah Kota Banjar Baru', 'is_active' => 1],
            ['id' => '6900', 'nama_instansi' => 'Pemerintah Provinsi Kalimantan Timur', 'is_active' => 1],
            ['id' => '6901', 'nama_instansi' => 'Pemerintah Kab. Kutai Kartanegara', 'is_active' => 1],
            ['id' => '6902', 'nama_instansi' => 'Pemerintah Kab. Paser', 'is_active' => 1],
            ['id' => '6904', 'nama_instansi' => 'Pemerintah Kab. Berau', 'is_active' => 1],
            ['id' => '6907', 'nama_instansi' => 'Pemerintah Kab. Kutai Barat', 'is_active' => 1],
            ['id' => '6908', 'nama_instansi' => 'Pemerintah Kab. Kutai Timur', 'is_active' => 1],
            ['id' => '6910', 'nama_instansi' => 'Pemerintah Kab. Penajam Paser Utara', 'is_active' => 1],
            ['id' => '6912', 'nama_instansi' => 'Pemerintah Kab. Mahakam Ulu', 'is_active' => 1],
            ['id' => '6971', 'nama_instansi' => 'Pemerintah Kota Samarinda', 'is_active' => 1],
            ['id' => '6972', 'nama_instansi' => 'Pemerintah Kota Balikpapan', 'is_active' => 1],
            ['id' => '6973', 'nama_instansi' => 'Pemerintah Kota Bontang', 'is_active' => 1],
            ['id' => '7000', 'nama_instansi' => 'Pemerintah Provinsi Sulawesi Utara', 'is_active' => 1],
            ['id' => '7001', 'nama_instansi' => 'Pemerintah Kab. Minahasa', 'is_active' => 1],
            ['id' => '7002', 'nama_instansi' => 'Pemerintah Kab. Bolaang Mongondow', 'is_active' => 1],
            ['id' => '7003', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Sangihe', 'is_active' => 1],
            ['id' => '7004', 'nama_instansi' => 'Pemerintah Kab. Minahasa Selatan', 'is_active' => 1],
            ['id' => '7005', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Talaud', 'is_active' => 1],
            ['id' => '7006', 'nama_instansi' => 'Pemerintah Kab. Minahasa Utara', 'is_active' => 1],
            ['id' => '7007', 'nama_instansi' => 'Pemerintah Kab. Bolaang Mongondow Utara', 'is_active' => 1],
            ['id' => '7008', 'nama_instansi' => 'Pemerintah Kab. Siau Tagulandang Biaro', 'is_active' => 1],
            ['id' => '7009', 'nama_instansi' => 'Pemerintah Kab. Minahasa Tenggara', 'is_active' => 1],
            ['id' => '7012', 'nama_instansi' => 'Pemerintah Kab. Bolaang Mongondow Selatan', 'is_active' => 1],
            ['id' => '7013', 'nama_instansi' => 'Pemerintah Kab. Bolaang Mongondow Timur', 'is_active' => 1],
            ['id' => '7071', 'nama_instansi' => 'Pemerintah Kota Manado', 'is_active' => 1],
            ['id' => '7072', 'nama_instansi' => 'Pemerintah Kota Bitung', 'is_active' => 1],
            ['id' => '7073', 'nama_instansi' => 'Pemerintah Kota Tomohon', 'is_active' => 1],
            ['id' => '7074', 'nama_instansi' => 'Pemerintah Kota KotaMobagu', 'is_active' => 1],
            ['id' => '7100', 'nama_instansi' => 'Pemerintah Provinsi Gorontalo', 'is_active' => 1],
            ['id' => '7101', 'nama_instansi' => 'Pemerintah Kab. Gorontalo', 'is_active' => 1],
            ['id' => '7102', 'nama_instansi' => 'Pemerintah Kab. Boalemo', 'is_active' => 1],
            ['id' => '7103', 'nama_instansi' => 'Pemerintah Kab. Pohuwato', 'is_active' => 1],
            ['id' => '7104', 'nama_instansi' => 'Pemerintah Kab. Bone Bolango', 'is_active' => 1],
            ['id' => '7105', 'nama_instansi' => 'Pemerintah Kab. Gorontalo Utara', 'is_active' => 1],
            ['id' => '7171', 'nama_instansi' => 'Pemerintah Kota Gorontalo', 'is_active' => 1],
            ['id' => '7200', 'nama_instansi' => 'Pemerintah Provinsi Sulawesi Tengah', 'is_active' => 1],
            ['id' => '7201', 'nama_instansi' => 'Pemerintah Kab. Poso', 'is_active' => 1],
            ['id' => '7202', 'nama_instansi' => 'Pemerintah Kab. Donggala', 'is_active' => 1],
            ['id' => '7203', 'nama_instansi' => 'Pemerintah Kab. Tolitoli', 'is_active' => 1],
            ['id' => '7204', 'nama_instansi' => 'Pemerintah Kab. Banggai', 'is_active' => 1],
            ['id' => '7205', 'nama_instansi' => 'Pemerintah Kab. Buol', 'is_active' => 1],
            ['id' => '7206', 'nama_instansi' => 'Pemerintah Kab. Morowali', 'is_active' => 1],
            ['id' => '7207', 'nama_instansi' => 'Pemerintah Kab. Banggai Kepulauan', 'is_active' => 1],
            ['id' => '7208', 'nama_instansi' => 'Pemerintah Kab. Parigi Moutong', 'is_active' => 1],
            ['id' => '7209', 'nama_instansi' => 'Pemerintah Kab. Tojo Una Una', 'is_active' => 1],
            ['id' => '7210', 'nama_instansi' => 'Pemerintah Kab. Sigi', 'is_active' => 1],
            ['id' => '7211', 'nama_instansi' => 'Pemerintah Kab. Banggai Laut', 'is_active' => 1],
            ['id' => '7271', 'nama_instansi' => 'Pemerintah Kota Palu', 'is_active' => 1],
            ['id' => '7300', 'nama_instansi' => 'Pemerintah Provinsi Sulawesi Selatan', 'is_active' => 1],
            ['id' => '7301', 'nama_instansi' => 'Pemerintah Kab. Pinrang', 'is_active' => 1],
            ['id' => '7302', 'nama_instansi' => 'Pemerintah Kab. Gowa', 'is_active' => 1],
            ['id' => '7303', 'nama_instansi' => 'Pemerintah Kab. Wajo', 'is_active' => 1],
            ['id' => '7305', 'nama_instansi' => 'Pemerintah Kab. Bone', 'is_active' => 1],
            ['id' => '7306', 'nama_instansi' => 'Pemerintah Kab. Tana Toraja', 'is_active' => 1],
            ['id' => '7307', 'nama_instansi' => 'Pemerintah Kab. Maros', 'is_active' => 1],
            ['id' => '7309', 'nama_instansi' => 'Pemerintah Kab. Luwu', 'is_active' => 1],
            ['id' => '7310', 'nama_instansi' => 'Pemerintah Kab. Sinjai', 'is_active' => 1],
            ['id' => '7311', 'nama_instansi' => 'Pemerintah Kab. Bulukumba', 'is_active' => 1],
            ['id' => '7312', 'nama_instansi' => 'Pemerintah Kab. Bantaeng', 'is_active' => 1],
            ['id' => '7313', 'nama_instansi' => 'Pemerintah Kab. Jeneponto', 'is_active' => 1],
            ['id' => '7314', 'nama_instansi' => 'Pemerintah Kabupaten Kepulauan Selayar', 'is_active' => 1],
            ['id' => '7315', 'nama_instansi' => 'Pemerintah Kab. Takalar', 'is_active' => 1],
            ['id' => '7316', 'nama_instansi' => 'Pemerintah Kab. Barru', 'is_active' => 1],
            ['id' => '7317', 'nama_instansi' => 'Pemerintah Kab. Sidenreng Rappang', 'is_active' => 1],
            ['id' => '7318', 'nama_instansi' => 'Pemerintah Kab. Pangkajene dan Kepulauan', 'is_active' => 1],
            ['id' => '7319', 'nama_instansi' => 'Pemerintah Kab. Soppeng', 'is_active' => 1],
            ['id' => '7321', 'nama_instansi' => 'Pemerintah Kab. Enrekang', 'is_active' => 1],
            ['id' => '7322', 'nama_instansi' => 'Pemerintah Kab. Luwu Utara', 'is_active' => 1],
            ['id' => '7325', 'nama_instansi' => 'Pemerintah Kab. Luwu Timur', 'is_active' => 1],
            ['id' => '7326', 'nama_instansi' => 'Pemerintah Kab. Toraja Utara', 'is_active' => 1],
            ['id' => '7371', 'nama_instansi' => 'Pemerintah Kota Makassar', 'is_active' => 1],
            ['id' => '7372', 'nama_instansi' => 'Pemerintah Kota Parepare', 'is_active' => 1],
            ['id' => '7373', 'nama_instansi' => 'Pemerintah Kota Palopo', 'is_active' => 1],
            ['id' => '7400', 'nama_instansi' => 'Pemerintah Provinsi Sulawesi Tenggara', 'is_active' => 1],
            ['id' => '7401', 'nama_instansi' => 'Pemerintah Kab. Konawe', 'is_active' => 1],
            ['id' => '7402', 'nama_instansi' => 'Pemerintah Kab. Buton', 'is_active' => 1],
            ['id' => '7403', 'nama_instansi' => 'Pemerintah Kab. Muna', 'is_active' => 1],
            ['id' => '7404', 'nama_instansi' => 'Pemerintah Kab. Kolaka', 'is_active' => 1],
            ['id' => '7405', 'nama_instansi' => 'Pemerintah Kab. Konawe Selatan', 'is_active' => 1],
            ['id' => '7406', 'nama_instansi' => 'Pemerintah Kab. Kolaka Utara', 'is_active' => 1],
            ['id' => '7407', 'nama_instansi' => 'Pemerintah Kab. Bombana', 'is_active' => 1],
            ['id' => '7408', 'nama_instansi' => 'Pemerintah Kab. Wakatobi', 'is_active' => 1],
            ['id' => '7410', 'nama_instansi' => 'Pemerintah Kab. Buton Utara', 'is_active' => 1],
            ['id' => '7411', 'nama_instansi' => 'Pemerintah Kab. Konawe Utara', 'is_active' => 1],
            ['id' => '7412', 'nama_instansi' => 'Pemerintah Kab. Kolaka Timur', 'is_active' => 1],
            ['id' => '7471', 'nama_instansi' => 'Pemerintah Kota Kendari', 'is_active' => 1],
            ['id' => '7472', 'nama_instansi' => 'Pemerintah Kota Baubau', 'is_active' => 1],
            ['id' => '7500', 'nama_instansi' => 'Pemerintah Provinsi Bali', 'is_active' => 1],
            ['id' => '7501', 'nama_instansi' => 'Pemerintah Kab. Buleleng', 'is_active' => 1],
            ['id' => '7502', 'nama_instansi' => 'Pemerintah Kab. Jembrana', 'is_active' => 1],
            ['id' => '7503', 'nama_instansi' => 'Pemerintah Kab. Klungkung', 'is_active' => 1],
            ['id' => '7504', 'nama_instansi' => 'Pemerintah Kab. Gianyar', 'is_active' => 1],
            ['id' => '7505', 'nama_instansi' => 'Pemerintah Kab. Karangasem', 'is_active' => 1],
            ['id' => '7506', 'nama_instansi' => 'Pemerintah Kab. Bangli', 'is_active' => 1],
            ['id' => '7507', 'nama_instansi' => 'Pemerintah Kab. Badung', 'is_active' => 1],
            ['id' => '7508', 'nama_instansi' => 'Pemerintah Kab. Tabanan', 'is_active' => 1],
            ['id' => '7571', 'nama_instansi' => 'Pemerintah Kota Denpasar', 'is_active' => 1],
            ['id' => '7600', 'nama_instansi' => 'Pemerintah Provinsi NTB', 'is_active' => 1],
            ['id' => '7601', 'nama_instansi' => 'Pemerintah Kab. Lombok Barat', 'is_active' => 1],
            ['id' => '7602', 'nama_instansi' => 'Pemerintah Kab. Lombok Tengah', 'is_active' => 1],
            ['id' => '7603', 'nama_instansi' => 'Pemerintah Kab. Lombok Timur', 'is_active' => 1],
            ['id' => '7604', 'nama_instansi' => 'Pemerintah Kab. Bima', 'is_active' => 1],
            ['id' => '7605', 'nama_instansi' => 'Pemerintah Kab. Sumbawa', 'is_active' => 1],
            ['id' => '7606', 'nama_instansi' => 'Pemerintah Kab. Dompu', 'is_active' => 1],
            ['id' => '7607', 'nama_instansi' => 'Pemerintah Kab. Sumbawa Barat', 'is_active' => 1],
            ['id' => '7608', 'nama_instansi' => 'Pemerintah Kab. Lombok Utara', 'is_active' => 1],
            ['id' => '7671', 'nama_instansi' => 'Pemerintah Kota Mataram', 'is_active' => 1],
            ['id' => '7672', 'nama_instansi' => 'Pemerintah Kota Bima', 'is_active' => 1],
            ['id' => '7700', 'nama_instansi' => 'Pemerintah Provinsi NTT', 'is_active' => 1],
            ['id' => '7701', 'nama_instansi' => 'Pemerintah Kab. Kupang', 'is_active' => 1],
            ['id' => '7702', 'nama_instansi' => 'Pemerintah Kab. Belu', 'is_active' => 1],
            ['id' => '7703', 'nama_instansi' => 'Pemerintah Kab. Timor Tengah Utara', 'is_active' => 1],
            ['id' => '7704', 'nama_instansi' => 'Pemerintah Kab. Timor Tengah Selatan', 'is_active' => 1],
            ['id' => '7705', 'nama_instansi' => 'Pemerintah Kab. Alor', 'is_active' => 1],
            ['id' => '7706', 'nama_instansi' => 'Pemerintah Kab. Sikka', 'is_active' => 1],
            ['id' => '7707', 'nama_instansi' => 'Pemerintah Kab. Flores Timur', 'is_active' => 1],
            ['id' => '7708', 'nama_instansi' => 'Pemerintah Kab. Ende', 'is_active' => 1],
            ['id' => '7709', 'nama_instansi' => 'Pemerintah Kab. Ngada', 'is_active' => 1],
            ['id' => '7710', 'nama_instansi' => 'Pemerintah Kab. Manggarai', 'is_active' => 1],
            ['id' => '7711', 'nama_instansi' => 'Pemerintah Kab. Sumba Timur', 'is_active' => 1],
            ['id' => '7712', 'nama_instansi' => 'Pemerintah Kab. Sumba Barat', 'is_active' => 1],
            ['id' => '7713', 'nama_instansi' => 'Pemerintah Kab. Lembata', 'is_active' => 1],
            ['id' => '7714', 'nama_instansi' => 'Pemerintah Kab. Rote Ndao', 'is_active' => 1],
            ['id' => '7715', 'nama_instansi' => 'Pemerintah Kab. Manggarai Barat', 'is_active' => 1],
            ['id' => '7716', 'nama_instansi' => 'Pemerintah Kab. Manggarai Timur', 'is_active' => 1],
            ['id' => '7717', 'nama_instansi' => 'Pemerintah Kab. Sumba Barat Daya', 'is_active' => 1],
            ['id' => '7718', 'nama_instansi' => 'Pemerintah Kab. Nagekeo', 'is_active' => 1],
            ['id' => '7719', 'nama_instansi' => 'Pemerintah Kab. Sumba Tengah', 'is_active' => 1],
            ['id' => '7720', 'nama_instansi' => 'Pemerintah Kabupaten Sabu Raijua', 'is_active' => 1],
            ['id' => '7721', 'nama_instansi' => 'Pemerintah Kab. Malaka', 'is_active' => 1],
            ['id' => '7771', 'nama_instansi' => 'Pemerintah Kota Kupang', 'is_active' => 1],
            ['id' => '7800', 'nama_instansi' => 'Pemerintah Provinsi Maluku', 'is_active' => 1],
            ['id' => '7801', 'nama_instansi' => 'Pemerintah Kab. Maluku Tengah', 'is_active' => 1],
            ['id' => '7802', 'nama_instansi' => 'Pemerintah Kab. Maluku Tenggara', 'is_active' => 1],
            ['id' => '7803', 'nama_instansi' => 'Pemerintah Kab. Buru', 'is_active' => 1],
            ['id' => '7804', 'nama_instansi' => 'Pemerintah Kab. Maluku Tenggara Barat', 'is_active' => 1],
            ['id' => '7805', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Aru', 'is_active' => 1],
            ['id' => '7806', 'nama_instansi' => 'Pemerintah Kab. Seram Bagian Barat', 'is_active' => 1],
            ['id' => '7807', 'nama_instansi' => 'Pemerintah Kab. Seram Bagian Timur', 'is_active' => 1],
            ['id' => '7808', 'nama_instansi' => 'Pemerintah Kab. Buru Selatan', 'is_active' => 1],
            ['id' => '7809', 'nama_instansi' => 'Pemerintah Kab. Maluku Barat Daya', 'is_active' => 1],
            ['id' => '7871', 'nama_instansi' => 'Pemerintah Kota Ambon', 'is_active' => 1],
            ['id' => '7872', 'nama_instansi' => 'Pemerintah Kota Tual', 'is_active' => 1],
            ['id' => '7900', 'nama_instansi' => 'Pemerintah Provinsi Maluku Utara', 'is_active' => 1],
            ['id' => '7901', 'nama_instansi' => 'Pemerintah Kab. Halmahera Barat', 'is_active' => 1],
            ['id' => '7902', 'nama_instansi' => 'Pemerintah Kab. Halmahera Tengah', 'is_active' => 1],
            ['id' => '7903', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Sula', 'is_active' => 1],
            ['id' => '7904', 'nama_instansi' => 'Pemerintah Kab. Halmahera Selatan', 'is_active' => 1],
            ['id' => '7905', 'nama_instansi' => 'Pemerintah Kab. Halmahera Utara', 'is_active' => 1],
            ['id' => '7906', 'nama_instansi' => 'Pemerintah Kab. Halmahera Timur', 'is_active' => 1],
            ['id' => '7907', 'nama_instansi' => 'Pemerintah Kab. Pulau Morotai', 'is_active' => 1],
            ['id' => '7908', 'nama_instansi' => 'Pemerintah Kab. Pulau Taliabu', 'is_active' => 1],
            ['id' => '7971', 'nama_instansi' => 'Pemerintah Kota Ternate', 'is_active' => 1],
            ['id' => '7972', 'nama_instansi' => 'Pemerintah Kota Tidore Kepulauan', 'is_active' => 1],
            ['id' => '8000', 'nama_instansi' => 'Pemerintah Provinsi Papua', 'is_active' => 1],
            ['id' => '8001', 'nama_instansi' => 'Pemerintah Kab. Jayapura', 'is_active' => 1],
            ['id' => '8002', 'nama_instansi' => 'Pemerintah Kab. Biak Numfor', 'is_active' => 1],
            ['id' => '8004', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Yapen', 'is_active' => 1],
            ['id' => '8007', 'nama_instansi' => 'Pemerintah Kab. Merauke', 'is_active' => 1],
            ['id' => '8008', 'nama_instansi' => 'Pemerintah Kab. Jayawijaya', 'is_active' => 1],
            ['id' => '8009', 'nama_instansi' => 'Pemerintah Kab. Nabire', 'is_active' => 1],
            ['id' => '8010', 'nama_instansi' => 'Pemerintah Kab. Puncak Jaya', 'is_active' => 1],
            ['id' => '8011', 'nama_instansi' => 'Pemerintah Kab. Paniai', 'is_active' => 1],
            ['id' => '8012', 'nama_instansi' => 'Pemerintah Kab. Mimika', 'is_active' => 1],
            ['id' => '8013', 'nama_instansi' => 'Pemerintah Kab. Boven Digoel', 'is_active' => 1],
            ['id' => '8014', 'nama_instansi' => 'Pemerintah Kab. Mappi', 'is_active' => 1],
            ['id' => '8015', 'nama_instansi' => 'Pemerintah Kab. Asmat', 'is_active' => 1],
            ['id' => '8016', 'nama_instansi' => 'Pemerintah Kab. Yahukimo', 'is_active' => 1],
            ['id' => '8017', 'nama_instansi' => 'Pemerintah Kab. Pegunungan Bintang', 'is_active' => 1],
            ['id' => '8018', 'nama_instansi' => 'Pemerintah Kab. Tolikara', 'is_active' => 1],
            ['id' => '8019', 'nama_instansi' => 'Pemerintah Kab. Sarmi', 'is_active' => 1],
            ['id' => '8020', 'nama_instansi' => 'Pemerintah Kab. Keerom', 'is_active' => 1],
            ['id' => '8026', 'nama_instansi' => 'Pemerintah Kab. Waropen', 'is_active' => 1],
            ['id' => '8027', 'nama_instansi' => 'Pemerintah Kab. Supiori', 'is_active' => 1],
            ['id' => '8028', 'nama_instansi' => 'Pemerintah Kab. Mamberamo Raya', 'is_active' => 1],
            ['id' => '8029', 'nama_instansi' => 'Pemerintah Kab. Mamberamo Tengah', 'is_active' => 1],
            ['id' => '8030', 'nama_instansi' => 'Pemerintah Kab. Lanny Jaya', 'is_active' => 1],
            ['id' => '8031', 'nama_instansi' => 'Pemerintah Kab. Yalimo', 'is_active' => 1],
            ['id' => '8032', 'nama_instansi' => 'Pemerintah Kab. Nduga', 'is_active' => 1],
            ['id' => '8033', 'nama_instansi' => 'Pemerintah Kab. Dogiyai', 'is_active' => 1],
            ['id' => '8035', 'nama_instansi' => 'Pemerintah Kab. Puncak', 'is_active' => 1],
            ['id' => '8036', 'nama_instansi' => 'Pemerintah Kab. Deiyai', 'is_active' => 1],
            ['id' => '8037', 'nama_instansi' => 'Pemerintah Kab. Intan Jaya', 'is_active' => 1],
            ['id' => '8072', 'nama_instansi' => 'Pemerintah Kota Jayapura', 'is_active' => 1],
            ['id' => '8100', 'nama_instansi' => 'Pemerintah Provinsi Kepulauan Riau', 'is_active' => 1],
            ['id' => '8101', 'nama_instansi' => 'Pemerintah Kab. Bintan', 'is_active' => 1],
            ['id' => '8102', 'nama_instansi' => 'Pemerintah Kab. Karimun', 'is_active' => 1],
            ['id' => '8103', 'nama_instansi' => 'Pemerintah Kab. Natuna', 'is_active' => 1],
            ['id' => '8104', 'nama_instansi' => 'Pemerintah Kab. Lingga', 'is_active' => 1],
            ['id' => '8105', 'nama_instansi' => 'Pemerintah Kab. Kepulauan Anambas', 'is_active' => 1],
            ['id' => '8171', 'nama_instansi' => 'Pemerintah Kota Batam', 'is_active' => 1],
            ['id' => '8172', 'nama_instansi' => 'Pemerintah Kota Tanjungpinang', 'is_active' => 1],
            ['id' => '8200', 'nama_instansi' => 'Pemerintah Provinsi Papua Barat', 'is_active' => 1],
            ['id' => '8201', 'nama_instansi' => 'Pemerintah Kab. Sorong', 'is_active' => 1],
            ['id' => '8202', 'nama_instansi' => 'Pemerintah Kab. Sorong Selatan', 'is_active' => 1],
            ['id' => '8203', 'nama_instansi' => 'Pemerintah Kab. Raja Ampat', 'is_active' => 1],
            ['id' => '8204', 'nama_instansi' => 'Pemerintah Kab. Manokwari', 'is_active' => 1],
            ['id' => '8205', 'nama_instansi' => 'Pemerintah Kab. Teluk Bintuni', 'is_active' => 1],
            ['id' => '8206', 'nama_instansi' => 'Pemerintah Kab. Teluk Wondama', 'is_active' => 1],
            ['id' => '8207', 'nama_instansi' => 'Pemerintah Kab. Fak-Fak', 'is_active' => 1],
            ['id' => '8208', 'nama_instansi' => 'Pemerintah Kab. Kaimana', 'is_active' => 1],
            ['id' => '8210', 'nama_instansi' => 'Pemerintah Kab. Tambrauw', 'is_active' => 1],
            ['id' => '8211', 'nama_instansi' => 'Pemerintah Kab. Maybrat', 'is_active' => 1],
            ['id' => '8212', 'nama_instansi' => 'Pemerintah Kab. Pegunungan Arfak', 'is_active' => 1],
            ['id' => '8271', 'nama_instansi' => 'Pemerintah Kota Sorong', 'is_active' => 1],
            ['id' => '8300', 'nama_instansi' => 'Pemerintah Provinsi Sulawesi Barat', 'is_active' => 1],
            ['id' => '8301', 'nama_instansi' => 'Pemerintah Kab. Mamuju Utara', 'is_active' => 1],
            ['id' => '8302', 'nama_instansi' => 'Pemerintah Kab. Mamuju', 'is_active' => 1],
            ['id' => '8303', 'nama_instansi' => 'Pemerintah Kab. Mamasa', 'is_active' => 1],
            ['id' => '8304', 'nama_instansi' => 'Pemerintah Kab. Polewali Mandar', 'is_active' => 1],
            ['id' => '8305', 'nama_instansi' => 'Pemerintah Kab. Majene', 'is_active' => 1],
            ['id' => '8306', 'nama_instansi' => 'Pemerintah Kab. Mamuju Tengah', 'is_active' =>. 1],
            ['id' => '8400', 'nama_instansi' => 'Pemerintah Provinsi Kalimantan Utara', 'is_active' => 1],
            ['id' => '8401', 'nama_instansi' => 'Pemerintah Kab. Bulungan', 'is_active' => 1],
            ['id' => '8402', 'nama_instansi' => 'Pemerintah Kab. Malinau', 'is_active' => 1],
            ['id' => '8403', 'nama_instansi' => 'Pemerintah Kab. Nunukan', 'is_active' => 1],
            ['id' => '8404', 'nama_instansi' => 'Pemerintah Kab. Tana Tidung', 'is_active' => 1],
            ['id' => '8471', 'nama_instansi' => 'Pemerintah Kota Tarakan', 'is_active' => 1],
            ['id' => '8810', 'nama_instansi' => 'BUMN', 'is_active' => 1],
            ['id' => '8820', 'nama_instansi' => 'BUMD', 'is_active' => 1],
            ['id' => '8830', 'nama_instansi' => 'SWASTA', 'is_active' => 1],
            ['id' => '9910', 'nama_instansi' => 'Luar Negeri', 'is_active' => 1],
            ['id' => '9999', 'nama_instansi' => 'Lain-Lain', 'is_active' => 1],
        ];

        // Using insertBatch for efficiency
        $this->db->table('ref_instansi')->insertBatch($data);
    }
}
